FROM ghcr.io/oracle/oraclelinux:8

COPY rpms /tmp/

RUN dnf install -y /tmp/*.rpm &&\
    dnf clean all &&\
    rm -rf /var/cache/yum/* /tmp/*.rpm &&\
    test -d /LICENSES || ln -s /usr/share/licenses /LICENSES

FROM ghcr.io/oracle/oraclelinux:8-slim

COPY --from=0 /usr/share/licenses/metallb* /LICENSES
COPY --from=0 /usr/local/share/olcne/metallb/metallb/mirror-server /usr/src/metallb/

WORKDIR /usr/src/metallb/

ENTRYPOINT ["./mirror-server"]