FROM ghcr.io/oracle/oraclelinux:8

COPY rpms /tmp/

RUN dnf install -y /tmp/*.rpm &&\
    dnf clean all &&\
    rm -rf /var/cache/yum/* /tmp/*.rpm &&\
    test -d /LICENSES || ln -s /usr/share/licenses /LICENSES

FROM ghcr.io/oracle/oraclelinux:8-slim

COPY --from=0 /usr/share/licenses/metallb* /LICENSES
COPY --from=0 /usr/local/share/olcne/metallb/metallb/controller /usr/src/metallb

WORKDIR /usr/src/metallb/

# When running as non root and building in an environment that `umask` masks out
# '+x' for others, it won't be possible to execute. Make sure all can execute,
# just in case
RUN chmod a+x controller

ENTRYPOINT ["./controller"]