

@Library('olcne-pipeline') _
import com.oracle.olcne.pipeline.BranchPattern

String metallb_version = "0.13.12"
String image_tag = 'v' + metallb_version

olcnePipeline(
  branchPattern: new BranchPattern(master: "oracle/release/" + metallb_version, feature: '(?!^release/.*$)(^.*$)'),
  containers: [
    ('container-registry.oracle.com/olcne/controller:' + image_tag)     : 'olcne/controller:' + image_tag,
    ('container-registry.oracle.com/olcne/speaker:' + image_tag)        : 'olcne/speaker:' + image_tag,
    ('container-registry.oracle.com/olcne/configmaptocrs:' + image_tag) : 'olcne/configmaptocrs:' + image_tag
  ],
  platforms: ['ol8', 'ol9'],
  architectures: ['x86_64', 'aarch64'],
  yumOL8Repos: ['ol8_appstream', 'ol8_developer'],
  ol8ModulesToDisable: ['go-toolset:ol8'],
  ol8ModulesToEnable: ['go-toolset:ol8addon'],
  yumOL9Repos: ['ol9_appstream', 'ol9_developer'],
  customPlatformStages: [
    customPlatformSteps: [
      ol8: [container: [enabled: true ], buildContainerRpms: [enabled: true ]],
      ol9: [container: [enabled: false ], buildContainerRpms: [enabled: false ]],
    ],
  ]
)

